---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	query_subgraph(query_subgraph)
	meaning_expand(meaning_expand)
	paper_retrieval(paper_retrieval)
	limitation_extract(limitation_extract)
	limitation_eval(limitation_eval)
	recency_check(recency_check)
	gap_infer(gap_infer)
	critic_score(critic_score)
	final_response(final_response)
	__end__([<p>__end__</p>]):::last
	__start__ --> query_subgraph;
	critic_score -.-> __end__;
	critic_score -.-> final_response;
	critic_score -.-> meaning_expand;
	critic_score -.-> query_subgraph;
	gap_infer --> critic_score;
	limitation_eval -.-> limitation_extract;
	limitation_eval -.-> recency_check;
	limitation_extract --> limitation_eval;
	meaning_expand --> paper_retrieval;
	paper_retrieval --> limitation_extract;
	query_subgraph --> meaning_expand;
	recency_check --> gap_infer;
	final_response --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
